#Server
server:
  port: ${SERVER_PORT:8083}
  servlet:
    contextPath: /api
    
ldap:
  url: ldap://localhost:10389
  base: ou=customers,o=touresbalon
  user: cn=Administrator,o=touresbalon
  password: ingeniero3118
  dn_principal: cn=%s,ou=customers,o=touresbalon
  
jwt:
  access_expires_in: 300
  refresh_expires_in: 600
  secret: ${JTW_SECRET:secret}
  
encrypt:
  publicKey: ETfl8BigpmxVie8wgB4fAo8zHCcHR3M2AJNux+6N8Rk=