DROP PROCEDURE PRODUCT_CONSULT;
GO
CREATE PROCEDURE PRODUCT_CONSULT
@ID BIGINT
AS
BEGIN
	SELECT * FROM PRODUCT
		WHERE ID = @ID 
			COMMIT;  
END
GO     
/*
DECLARE @NAME varchar(30)
SET @NAME = 'BARCELONA'
	SELECT * FROM PRODUCT
		WHERE NAME LIKE '%'+ @name +'%' 
*/