server:
  port: ${PORT:8787}

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  level:
      - ".=info"
      - "com.memorynotfound=debug"
      - "org.springframework=info"