#Server
server:
  port: ${SERVER_PORT:8082}
  servlet:
    contextPath: /api
    
osb:
  endpointOrder: http://25.70.184.165:7003/OrderService/order
  endpointCustomer: http://25.70.184.165:7003/OrderService/order 
  readTimeout: 5000
  connectTimeout: 2000
  
jwt: 
  secret: ${JTW_SECRET:secret}
  
encrypt:
  publicKey: ETfl8BigpmxVie8wgB4fAo8zHCcHR3M2AJNux+6N8Rk=