use DB_PRODUCT
go
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 1,'Campaña Especial',  5,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +60, GETDATE()),' 1.png', 1,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 2,'Campaña Especial', 10,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +90, GETDATE()),' 2.png', 2,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 3,'Campaña Especial', 15,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +120, GETDATE()),' 3.png', 3,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 4,'Campaña Especial', 20,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +60, GETDATE()),' 4.png', 4,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 5,'Campaña Especial', 25,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +90, GETDATE()),' 5.png', 5,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 6,'Campaña Especial',  5,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +120, GETDATE()),' 6.png', 6,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 7,'Campaña Especial', 10,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +60, GETDATE()),' 7.png', 7,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 8,'Campaña Especial', 15,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +90, GETDATE()),' 8.png', 8,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values ( 9,'Campaña Especial', 20,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +120, GETDATE()),' 9.png', 9,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (10,'Campaña Especial', 25,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +60, GETDATE()),'10.png',10,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (11,'Campaña Especial',  5,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +90, GETDATE()),'11.png',11,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (12,'Campaña Especial', 10,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +120, GETDATE()),'12.png',12,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (13,'Campaña Especial', 15,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +60, GETDATE()),'13.png',13,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (14,'Campaña Especial', 20,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +90, GETDATE()),'14.png',14,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (15,'Campaña Especial', 25,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +60, GETDATE()),'15.png',15,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (16,'Campaña Especial',  5,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +90, GETDATE()),'16.png',16,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (17,'Campaña Especial', 10,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +120, GETDATE()),'17.png',17,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (18,'Campaña Especial', 15,  GETDATE(),GETDATE(),DATEADD(DAY,-90,GETDATE()),DATEADD(DAY, +60, GETDATE()),'18.png',18,0);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (19,'Campaña Especial', 20,  GETDATE(),GETDATE(),DATEADD(DAY,-30,GETDATE()),DATEADD(DAY, +90, GETDATE()),'19.png',19,1);
INSERT INTO CAMPANA (id,name,percentage,create_date,update_date,start_date,effective_date,image_ref,product_id,is_active) Values (20,'Campaña Especial', 25,  GETDATE(),GETDATE(),DATEADD(DAY,-60,GETDATE()),DATEADD(DAY, +120, GETDATE()),'20.png',20,0);


