<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/TECH_ADAPTERS/dbDeleteCustomer" name="dbDeleteCustomer-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbDeleteCustomer.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/TECH_ADAPTERS/dbDeleteCustomer"/>
    <wsdl:binding name="dbDeleteCustomer_ptt-binding" type="dbd:dbDeleteCustomer_ptt" xmlns:dbd="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/TECH_ADAPTERS/dbDeleteCustomer">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbDeleteCustomer">
            <soap:operation soapAction="dbDeleteCustomer"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>