<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteItem" name="db_DeleteItem-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="db_DeleteItem.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteItem"/>
    <wsdl:binding name="db_DeleteItem_ptt-binding" type="db:db_DeleteItem_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteItem">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="db_DeleteItem">
            <soap:operation soapAction="db_DeleteItem"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>