<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_GetItem" name="db_GetItem-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="db_GetItem.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_GetItem"/>
    <wsdl:binding name="db_GetItem_ptt-binding" type="db:db_GetItem_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_GetItem">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="db_GetItem">
            <soap:operation soapAction="db_GetItem"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>