<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbGetItemOrder" name="dbGetItemOrder-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbGetItemOrder.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbGetItemOrder"/>
    <wsdl:binding name="dbGetItemOrder_ptt-binding" type="dbg:dbGetItemOrder_ptt" xmlns:dbg="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbGetItemOrder">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbGetItemOrder">
            <soap:operation soapAction="dbGetItemOrder"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>