<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ServicioWebAvianca"
	targetNamespace="http://avianca.com/schema/avainca/ServicioWebAvianca"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:ns2="http://avianca.com/schema/avainca/ServicioWebAvianca">
	<wsdl:types>
		<xsd:schema xmlns:tns="http://avianca.com/schema/avainca/ServicioWebAvianca">
			<xsd:import namespace="http://avianca.com/schema/avainca/ServicioWebAvianca"
				schemaLocation="AviancaOperations.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="CreateBooking">
		<wsdl:part element="ns2:CreateBooking" name="parameters" />
	</wsdl:message>
	<wsdl:message name="CreateBookingResponse">
		<wsdl:part element="ns2:CreateBookingResponse"
			name="parameters" />
	</wsdl:message>
	<wsdl:message name="CancelBooking">
		<wsdl:part element="ns2:CancelBooking" name="parameters" />
	</wsdl:message>
	<wsdl:message name="CancelBookingResponse">
		<wsdl:part element="ns2:CancelBookingResponse"
			name="parameters" />
	</wsdl:message>
	<wsdl:portType name="ServicioWebAvianca">
		<wsdl:operation name="CreateBooking">
			<wsdl:input message="ns2:CreateBooking" />
			<wsdl:output message="ns2:CreateBookingResponse" />
		</wsdl:operation>
		<wsdl:operation name="CancelBooking">
			<wsdl:input message="ns2:CancelBooking" />
			<wsdl:output message="ns2:CancelBookingResponse" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ServicioWebAviancaSOAP"
		type="ns2:ServicioWebAvianca">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="CreateBooking">
			<soap:operation
				soapAction="http://avianca.com/schema/avainca/ServicioWebAvianca/CreateBooking" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="CancelBooking">
			<soap:operation
				soapAction="http://avianca.com/schema/avainca/ServicioWebAvianca/CancelBooking" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ServicioWebAvianca">
		<wsdl:port binding="ns2:ServicioWebAviancaSOAP"
			name="ServicioWebAviancaSOAP">
			<soap:address location="http://avianca.com/schema/avainca/ServicioWebAvianca" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
