<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_CreateOrder" name="db_CreateOrder-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="db_CreateOrder.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_CreateOrder"/>
    <wsdl:binding name="db_CreateOrder_ptt-binding" type="db:db_CreateOrder_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_CreateOrder">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="db_CreateOrder">
            <soap:operation soapAction="db_CreateOrder"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>