<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteOrder" name="db_DeleteOrder-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="db_DeleteOrder.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteOrder"/>
    <wsdl:binding name="db_DeleteOrder_ptt-binding" type="db:db_DeleteOrder_ptt" xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/db_DeleteOrder">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="db_DeleteOrder">
            <soap:operation soapAction="db_DeleteOrder"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>