<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbUpdateOrder" name="dbUpdateOrder-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbUpdateOrder.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbUpdateOrder"/>
    <wsdl:binding name="dbUpdateOrder_ptt-binding" type="dbup:dbUpdateOrder_ptt" xmlns:dbup="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/OrderService/dbUpdateOrder">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbUpdateOrder">
            <soap:operation soapAction="dbUpdateOrder"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>