<wsdl:definitions
     name="dbCreateOrders"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/TECH_ADAPTERS/dbCreateOrders"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_BACK/TECH_ADAPTERS/dbCreateOrders"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbCreateOrders"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbCreateOrders_plt" >
    <plt:role name="dbCreateOrders_role" >
      <plt:portType name="tns:dbCreateOrders_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
     <schema xmlns="http://www.w3.org/2001/XMLSchema">
       <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/sp/dbCreateOrders"
               schemaLocation="dbCreateOrders_sp.xsd" />
     </schema>
    </wsdl:types>
    <wsdl:message name="args_in_msg">
        <wsdl:part name="InputParameters" element="db:InputParameters"/>
    </wsdl:message>
    <wsdl:message name="args_out_msg">
        <wsdl:part name="OutputParameters" element="db:OutputParameters"/>
    </wsdl:message>
    <wsdl:portType name="dbCreateOrders_ptt">
        <wsdl:operation name="dbCreateOrders">
            <wsdl:input message="tns:args_in_msg"/>
            <wsdl:output message="tns:args_out_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
