version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=node1
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.1
    container_name: elasticsearch2
    environment:
      - cluster.name=elasticsearch-cluster
      - node.name=node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - esnet
    depends_on: 
      - elasticsearch      
  logstash:
    image: andersbarrios/logstash-touresbalon
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      - TZ: "America/Bogota"
      - DB_HOST=192.168.43.155
      - DB_PORT=1433
      - DB_NAME=DB_PRODUCT
      - DB_USER=sa
      - DB_PASSWORD=adminadmin123
      #- "DB_STATEMENT=SELECT * FROM Users WHERE CREATION_DATE >= :sql_last_value"
      - "DB_STATEMENT=SELECT p.id, p.spectacle_date as spactacleDate, p.arrival_date as arrivalDate, p.departure_date as departureDate, t.name as transport,  s.name as spactacle,  l.name as lodging,  p.description,  p.image_ref as image,  co.name_city as sourceCity,  cd.name_city as targetCity FROM product p ,city co ,city cd ,spectacle s, transport T, lodging l WHERE p.target_city = cd.id and p.source_city = co.id and p.spectacle_type = s.id and P.transport_type = T.id and p.lodging_type = l.id and (p.create_date >= :sql_last_value or p.update_date >= :sql_last_value) ORDER BY p.id"
      - TRACKING_COLUMN=update_date
      - ES_INDEX=products
      - "CRON_PATTERN=*/5 * * * *"
    networks:
      - esnet
networks:
  esnet:
