#Server
server:
  port: ${SERVER_PORT:8081}
  servlet:
    contextPath: /products
elasticParameters:
  server: ${HOST:52.71.119.146}
  port: ${PORT:9200}
  index:
    products: ${INDEX_PRODUCTS:products}
    campaigns: ${INDEX_CAMPAIGNS:campaigns}
  searchSize: ${SEARCH_SIZE:50}